sudo: required
services:
  - docker

before_install:
  - docker build -t ganuelito/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true ganuelito/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-391444021157"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"